### ISSUE TITLE
When I run train.py

### ISSUE THREAD

**Issue by hawk90** [XenderLiu/MalConv-Pytorch#1]
pytorch version: 0.4.0
pandas version: 0.24.1

python3 train.py config/example.yaml 123
-->
Experiment:
	 example_sd_123
Training Set:
	Total 2 files
	Malware Count : 1
	Goodware Count: 1
Validation Set:
	Total 2 files
	Malware Count : 1
	Goodware Count: 1
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    history['tr_loss'].append(loss.cpu().data.numpy()[0])
IndexError: too many indices for array

**Comment by hawk90** [comment]
I changed it.

File "train.py", line 151, in <module>
     history['tr_loss'].append(loss.cpu().data.numpy()[0])
--> history['tr_loss'].append(loss.cpu().data.numpy())

File "train.py", line 183, in <module>
    history['val_loss'].append(loss.cpu().data.numpy()[0])
--> history['val_loss'].append(loss.cpu().data.numpy())
